[package]
name = "rstcontrol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial2={git="https://github.com/de-vri-es/serial2-rs"}
termion="2.0.1"
